[project]
name = "memoire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==5.1.8",
    "pgvector>=0.4.0",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.3",
    "celery>=5.5.0",
    "redis>=5.2.1",
]
