# Generated by Django 5.1.7 on 2025-03-31 15:22

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('custom_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255, null=True)),
                ('server_id', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('metadata', models.JSONField()),
                ('embeddings', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='memory.userprofile')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embeddings'], m=16, name='memory_embeddings_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['user', 'channel_id', 'server_id'], name='memory_memo_user_id_8d26e1_idx')],
            },
        ),
    ]
