# Generated by Django 5.1.7 on 2025-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_memory_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
    ]
