# Generated by Django 5.1.7 on 2025-04-01 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_memory_summarized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='summarized',
        ),
        migrations.AddField(
            model_name='memory',
            name='summary_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarized_memories', to='memory.memory'),
        ),
    ]
