# Generated by Django 5.1.7 on 2025-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_remove_memory_summarized_memory_summary_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='summary_of',
            new_name='summary_id',
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['summary_id'], name='memory_memo_summary_1be00b_idx'),
        ),
    ]
