# Generated by Django 5.1.7 on 2025-04-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_rename_summary_of_memory_summary_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='summary_id',
            new_name='summary',
        ),
        migrations.RenameIndex(
            model_name='memory',
            new_name='memory_memo_summary_026ae6_idx',
            old_name='memory_memo_summary_1be00b_idx',
        ),
    ]
